/**
 * Common IANA timezones for profile selection (grouped by region).
 */
export const PROFILE_TIMEZONE_OPTIONS: { value: string; label: string; region: string }[] = [
  { region: "North America", value: "America/New_York", label: "Eastern Time (US & Canada)" },
  { region: "North America", value: "America/Chicago", label: "Central Time (US & Canada)" },
  { region: "North America", value: "America/Denver", label: "Mountain Time (US & Canada)" },
  { region: "North America", value: "America/Los_Angeles", label: "Pacific Time (US & Canada)" },
  { region: "North America", value: "America/Anchorage", label: "Alaska" },
  { region: "North America", value: "Pacific/Honolulu", label: "Hawaii" },
  { region: "North America", value: "America/Toronto", label: "Toronto" },
  { region: "North America", value: "America/Vancouver", label: "Vancouver" },
  { region: "North America", value: "America/Mexico_City", label: "Mexico City" },
  { region: "South America", value: "America/Sao_Paulo", label: "São Paulo" },
  { region: "South America", value: "America/Buenos_Aires", label: "Buenos Aires" },
  { region: "South America", value: "America/Bogota", label: "Bogotá" },
  { region: "Europe", value: "Europe/London", label: "London" },
  { region: "Europe", value: "Europe/Dublin", label: "Dublin" },
  { region: "Europe", value: "Europe/Paris", label: "Paris" },
  { region: "Europe", value: "Europe/Berlin", label: "Berlin" },
  { region: "Europe", value: "Europe/Amsterdam", label: "Amsterdam" },
  { region: "Europe", value: "Europe/Madrid", label: "Madrid" },
  { region: "Europe", value: "Europe/Rome", label: "Rome" },
  { region: "Europe", value: "Europe/Zurich", label: "Zurich" },
  { region: "Europe", value: "Europe/Stockholm", label: "Stockholm" },
  { region: "Europe", value: "Europe/Warsaw", label: "Warsaw" },
  { region: "Europe", value: "Europe/Athens", label: "Athens" },
  { region: "Europe", value: "Europe/Istanbul", label: "Istanbul" },
  { region: "Europe", value: "Europe/Moscow", label: "Moscow" },
  { region: "Africa", value: "Africa/Lagos", label: "Lagos" },
  { region: "Africa", value: "Africa/Johannesburg", label: "Johannesburg" },
  { region: "Africa", value: "Africa/Nairobi", label: "Nairobi" },
  { region: "Africa", value: "Africa/Cairo", label: "Cairo" },
  { region: "Middle East", value: "Asia/Dubai", label: "Dubai" },
  { region: "Middle East", value: "Asia/Riyadh", label: "Riyadh" },
  { region: "Middle East", value: "Asia/Jerusalem", label: "Jerusalem" },
  { region: "Asia", value: "Asia/Kolkata", label: "India (IST)" },
  { region: "Asia", value: "Asia/Karachi", label: "Karachi" },
  { region: "Asia", value: "Asia/Dhaka", label: "Dhaka" },
  { region: "Asia", value: "Asia/Bangkok", label: "Bangkok" },
  { region: "Asia", value: "Asia/Singapore", label: "Singapore" },
  { region: "Asia", value: "Asia/Hong_Kong", label: "Hong Kong" },
  { region: "Asia", value: "Asia/Shanghai", label: "Shanghai" },
  { region: "Asia", value: "Asia/Tokyo", label: "Tokyo" },
  { region: "Asia", value: "Asia/Seoul", label: "Seoul" },
  { region: "Asia", value: "Asia/Manila", label: "Manila" },
  { region: "Oceania", value: "Australia/Sydney", label: "Sydney" },
  { region: "Oceania", value: "Australia/Melbourne", label: "Melbourne" },
  { region: "Oceania", value: "Australia/Perth", label: "Perth" },
  { region: "Oceania", value: "Pacific/Auckland", label: "Auckland" },
  { region: "UTC", value: "UTC", label: "UTC" },
];
